#!/bin/sh
'''exec' C:/Users/kunal/Desktop/AI_ML/sample_project1/env/bin/python "$0" "$@"
' '''
import sys
from nbclient.cli import main
if __name__ == '__main__':
    if sys.argv[0].endswith('.exe'):
        sys.argv[0] = sys.argv[0][:-4]
    sys.exit(main())
